spring:
  datasource:
    url: jdbc:h2:./appdb
    username: sa
    password:

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  thymeleaf:
    check-template-location: false

server:
  port: 8082